<a href="https://colab.research.google.com/github/komalsathvik/DeepLearning/blob/main/ANN/ANN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/DateFruit_Dataset.csv")
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [ ]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [ ]:
df.shape

(898, 35)

In [ ]:
x=df.drop("Class",axis=1)
y=df["Class"]

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader,TensorDataset

In [ ]:
x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [ ]:
train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
test_dataset=TensorDataset(x_test_tensor,y_test_tensor)

In [ ]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=False)

In [ ]:
#modelbuilding
class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()
    self.model=nn.Sequential(
        nn.Linear(x.shape[1],64),
        nn.ReLU(),
        nn.Linear(64,64),
        nn.ReLU(),
        nn.Linear(64,7)
    )
  def forward(self,x):
    return self.model(x)

In [ ]:
model=ANN()

#loss and optim
criteria=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [ ]:
#Training the ANN
epochs=100
for epoch in range(epochs):
  model.train()

  running_loss=0.0
  for xb,yb in train_loader:
    optimizer.zero_grad()
    outputs=model(xb)
    loss=criteria(outputs,yb)
    loss.backward()
    optimizer.step()
    running_loss+=loss.item()
  train_loss=running_loss/len(train_loader)
  print(f"Epoch {epoch}/{epochs}, Train Loss: {train_loss:.4f}")

Epoch 0/100, Train Loss: 0.0001
Epoch 1/100, Train Loss: 0.0001
Epoch 2/100, Train Loss: 0.0001
Epoch 3/100, Train Loss: 0.0001
Epoch 4/100, Train Loss: 0.0001
Epoch 5/100, Train Loss: 0.0001
Epoch 6/100, Train Loss: 0.0001
Epoch 7/100, Train Loss: 0.0001
Epoch 8/100, Train Loss: 0.0001
Epoch 9/100, Train Loss: 0.0001
Epoch 10/100, Train Loss: 0.0001
Epoch 11/100, Train Loss: 0.0001
Epoch 12/100, Train Loss: 0.0001
Epoch 13/100, Train Loss: 0.0001
Epoch 14/100, Train Loss: 0.0001
Epoch 15/100, Train Loss: 0.0001
Epoch 16/100, Train Loss: 0.0001
Epoch 17/100, Train Loss: 0.0000
Epoch 18/100, Train Loss: 0.0000
Epoch 19/100, Train Loss: 0.0001
Epoch 20/100, Train Loss: 0.0001
Epoch 21/100, Train Loss: 0.0000
Epoch 22/100, Train Loss: 0.0001
Epoch 23/100, Train Loss: 0.0001
Epoch 24/100, Train Loss: 0.0000
Epoch 25/100, Train Loss: 0.0000
Epoch 26/100, Train Loss: 0.0000
Epoch 27/100, Train Loss: 0.0000
Epoch 28/100, Train Loss: 0.0000
Epoch 29/100, Train Loss: 0.0000
Epoch 30/100, Train Loss: 0.0000
Epoch 31/100, Train Loss: 0.0000
Epoch 32/100, Train Loss: 0.0000
Epoch 33/100, Train Loss: 0.0000
Epoch 34/100, Train Loss: 0.0000
Epoch 35/100, Train Loss: 0.0000
Epoch 36/100, Train Loss: 0.0000
Epoch 37/100, Train Loss: 0.0000
Epoch 38/100, Train Loss: 0.0000
Epoch 39/100, Train Loss: 0.0000
Epoch 40/100, Train Loss: 0.0000
Epoch 41/100, Train Loss: 0.0000
Epoch 42/100, Train Loss: 0.0000
Epoch 43/100, Train Loss: 0.0000
Epoch 44/100, Train Loss: 0.0000
Epoch 45/100, Train Loss: 0.0000
Epoch 46/100, Train Loss: 0.0000
Epoch 47/100, Train Loss: 0.0000
Epoch 48/100, Train Loss: 0.0000
Epoch 49/100, Train Loss: 0.0000
Epoch 50/100, Train Loss: 0.0000
Epoch 51/100, Train Loss: 0.0000
Epoch 52/100, Train Loss: 0.0000
Epoch 53/100, Train Loss: 0.0000
Epoch 54/100, Train Loss: 0.0000
Epoch 55/100, Train Loss: 0.0000
Epoch 56/100, Train Loss: 0.0000
Epoch 57/100, Train Loss: 0.0000
Epoch 58/100, Train Loss: 0.0000
Epoch 59/100, Train Loss: 0.0000
Epoch 60/100, Train Loss: 0.0000
Epoch 61/100, Train Loss: 0.0000
Epoch 62/100, Train Loss: 0.0000
Epoch 63/100, Train Loss: 0.0000
Epoch 64/100, Train Loss: 0.0000
Epoch 65/100, Train Loss: 0.0000
Epoch 66/100, Train Loss: 0.0000
Epoch 67/100, Train Loss: 0.0000
Epoch 68/100, Train Loss: 0.0000
Epoch 69/100, Train Loss: 0.0000
Epoch 70/100, Train Loss: 0.0000
Epoch 71/100, Train Loss: 0.0000
Epoch 72/100, Train Loss: 0.0000
Epoch 73/100, Train Loss: 0.0000
Epoch 74/100, Train Loss: 0.0000
Epoch 75/100, Train Loss: 0.0000
Epoch 76/100, Train Loss: 0.0000
Epoch 77/100, Train Loss: 0.0000
Epoch 78/100, Train Loss: 0.0000
Epoch 79/100, Train Loss: 0.0000
Epoch 80/100, Train Loss: 0.0000
Epoch 81/100, Train Loss: 0.0000
Epoch 82/100, Train Loss: 0.0000
Epoch 83/100, Train Loss: 0.0000
Epoch 84/100, Train Loss: 0.0000
Epoch 85/100, Train Loss: 0.0000
Epoch 86/100, Train Loss: 0.0000
Epoch 87/100, Train Loss: 0.0000
Epoch 88/100, Train Loss: 0.0000
Epoch 89/100, Train Loss: 0.0000
Epoch 90/100, Train Loss: 0.0000
Epoch 91/100, Train Loss: 0.0000
Epoch 92/100, Train Loss: 0.0000
Epoch 93/100, Train Loss: 0.0000
Epoch 94/100, Train Loss: 0.0000
Epoch 95/100, Train Loss: 0.0000
Epoch 96/100, Train Loss: 0.0000
Epoch 97/100, Train Loss: 0.0000
Epoch 98/100, Train Loss: 0.0000
Epoch 99/100, Train Loss: 0.0000

In [47]:
model.eval()
total=0
correct=0

with torch.no_grad():
  for xb,yb in test_loader:
    outputs=model(xb)
    _,predicted=torch.max(outputs,1)

    correct+=(predicted==yb).sum().item()
    total+=(yb.size(0))
print(f"total={total},  correct={correct}")
accuracy=correct/total
print(f"Accuracy: {accuracy:.4f}")

total=180,  correct=169
Accuracy: 0.9389